stages:
  - build
  # - deploy

before_script:
  - python --version

build_job:
  stage: build  
  image: python:3.9
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

  artifacts:
    paths:
      - dist/


# pages:
#   script:
#     - pip install sphinx sphinx-rtd-theme
#     - cd doc
#     - make html
#     - mv build/html/ ../public/
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
