stages:
  - build
  - deploy

before_script:
  - python --version

build_job:
  stage: build    
  image: python:3.8
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  artifacts:
    paths:
    - venv/
    - requirements.txt

deploy_job: 
  stage: deploy  
  image: mcr.microsoft.com/azure-cli
  dependencies:
    - build_job
  before_script:
    - 'cd venv'
    - 'zip -r ./artifacts.zip .'  
    - 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID'
    - 'az account set --subscription $AZURE_SUBSCRIPTION_ID'
  script:
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src ./artifacts.zip
